server:
  port: 3000
  # Configurações para PCs lentos durante inicialização do PostgreSQL
  shutdown: graceful
  tomcat:
    # Timeout para conexões HTTP mais longas
    connection-timeout: 60s
    # Threads para lidar com requests
    threads:
      max: 50
      min-spare: 10

spring:
  config:
    # tentar carregar secrets do filesystem durante desenvolvimento e, quando empacotado,
    # permitir fallback para classpath (ex: recursos embutidos em produção/electron)
    import: optional:file:./secrets/application-secrets.yml,optional:file:./secrets/application-secrets.properties,optional:classpath:application-secrets.yml
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    # Configurações para aguardar PostgreSQL inicializar em PCs lentos
    hikari:
      connection-timeout: 60000 # 60 segundos para conectar
      initialization-fail-timeout: 120000 # 2 minutos para inicialização falhar
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false # Desabilitar completamente as propriedades padrão do DevTools
  jpa:
    hibernate:
      ddl-auto: update # Permitir criação/atualização temporariamente para desenvolvimento
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          "[time_zone]": "UTC"
    open-in-view: false
  liquibase:
    enabled: false # Temporariamente desabilitado para desenvolvimento
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-please-change-me-0123456789-ABCDEFGHIJKLMNOPQRSTUVWXYZ}
    expiration: 86400000 # 24h em ms
  # PostgreSQL backup/restore tools paths
  pgDumpPath: ${PG_DUMP_PATH:pg_dump}
  pgRestorePath: ${PG_RESTORE_PATH:pg_restore}
  backupDir: ${BACKUP_DIR:backups}
  enableDatabaseReset: ${ENABLE_DATABASE_RESET:false}

# CORS permissivo similar ao Express
cors:
  # Usamos allowed-origin-patterns internamente quando '*' para cobrir IPs/dominios variados e 'null' origin (apps desktop/webviews)
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers"
  exposed-headers: "Content-Length,X-Foo,X-Bar"
  allow-credentials: true
  max-age: 86400

logging:
  level:
    root: INFO
    "[org.springframework.web]": INFO
    "[com.example.backendspring]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    # Only log to file if LOG_FILE environment variable is set
    name: ${LOG_FILE:}
