############################################################
# Exemplo de arquivo de segredos (NÃO COMMITAR o real)
# Copie para: backend-spring/secrets/application-secrets.yml
# e ajuste os valores locais. O diretório `backend-spring/secrets` está ignorado no Git.
############################################################

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: change_me

app:
  jwt:
    secret: change_me_to_a_strong_random_secret_with_32+_chars
