server:
  port: 3000

spring:
  config:
    # tentar carregar secrets do filesystem durante desenvolvimento e, quando empacotado,
    # permitir fallback para classpath (ex: recursos embutidos em produção/electron)
    import: optional:file:./secrets/application-secrets.yml,optional:file:./secrets/application-secrets.properties,optional:classpath:application-secrets.yml
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          "[time_zone]": "UTC"
    open-in-view: false
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-please-change-me-0123456789-ABCDEFGHIJKLMNOPQRSTUVWXYZ}
    expiration: 86400000 # 24h em ms

# CORS permissivo similar ao Express
cors:
  # Usamos allowed-origin-patterns internamente quando '*' para cobrir IPs/dominios variados e 'null' origin (apps desktop/webviews)
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers"
  exposed-headers: "Content-Length,X-Foo,X-Bar"
  allow-credentials: true
  max-age: 86400

logging:
  level:
    root: INFO
    "[org.springframework.web]": INFO
    "[com.example.backendspring]": DEBUG
  file:
    # If LOG_FILE env var is set, logs will also be written to that file
    name: ${LOG_FILE:../backend.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
